apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zhishu-mingxi-state
  namespace: zhishu-mingxi
  labels:
    app.kubernetes.io/name: zhishu-mingxi-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 3Gi
